### ISSUE TITLE
Support Cucumber-JVM v6

### ISSUE THREAD

**Issue by aslakhellesoy** [SmartBear/cucumber-jvm-zephyr-xml#9]
How to do this:

* Create a v4 branch so we can keep maintaining the v4 release
* Create a diff between the original file v4 was forked from and the current one:
  * https://github.com/cucumber/cucumber-jvm/blob/v4.2.6/core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
  * https://github.com/SmartBear/cucumber-jvm-zephyr-xml/blob/master/src/main/java/io/cucumber/zephyr/ZephyrXMLFormatter.java
* Copy the latest `JunitFormatter.java` from `cucumber-jvm` into `ZephyrXMLFormatter.java`
  * https://github.com/cucumber/cucumber-jvm/blob/main/core/src/main/java/io/cucumber/core/plugin/JUnitFormatter.java
* Apply the diff (this may have to be done manually)
* Manually test...

**Comment by aslakhellesoy** [comment]
@milanverma do you have any questions about how to do this?

**Comment by arunahk** [comment]
Is someone working on this?

**Comment by aslakhellesoy** [comment]
Not that I know of @arunahk
